### ISSUE TITLE
Torpedo ahoy!

### ISSUE THREAD

**Issue by alto777** [david-c14/Torpedo#1]
I was thinking about this but it is above my pay grade, so thanks. 

You have a /res folder in your /src folder, looks like duplicates of ../res. I removed it and built your stuff just fine.

I thought first that you had designed a distinct port *.svg, but you use them for CVs also. I think you should think up a very distinct port *.svg that would clearly show something to be a data port. Switch the CV ports' appearance back to default.

I hope I find it as easy to deploy and use as it looks. Nice work! I just stumbled upon it, don't know where you've talked it up I imagine it will get used.

a7

**Comment by david-c14** [comment]
The src/res folder has all the text as text objects. I use inkscape to flatten the text because vcv cannot directly render the text, but I include the flattened res files because not everyone has inkscape.

**Comment by david-c14** [comment]
I used a grey tinted port for torpedo, and usually a white port for everything else. I may have mistaken them in the demos.

I don't use the default ports because I might want to make some commercial modules in the future, and keeping the style consistent would be simpler without having to negotiate a licence for the standard graphics.

**Comment by david-c14** [comment]
There are more demo apps on the way, and more documentatio. The TorPatch is pretty comprehensive. TorStore is a simpler demo to follow, cutting out a lot of unnecessary stuff. Feel free to ask questions if you need to, start a new thread for each.

**Comment by alto777** [comment]
Yes, I see. I try to keep the "text as text objects" SVGs around also, usually forget and curse.

I understand the desire to have custom jacks, I might have mentioned that I see this in other modules, it can make a distinctive look, very nice.

And I now notice the grey/not grey difference - that is now that I know what to look for. Missed that, so I still think you should go for something quite different I'm not good at imagining just what, but perhaps something with an apron that would also nicely incorporate your tiny lamps. Or pentangular. I don't know.

Anyway, good stuff. 

a7
